### ISSUE TITLE
The url in README can not be accessed

### ISSUE THREAD

**Issue by empqruy** [willsongbo/hello-odl#1]
The url https://www.jianshu.com/p/4b76e8dfc21e in the READMEcould not be accessed, page not exists.

BTW:  Any hello demo for the latest ODL version(Sodium)?  :)

**Comment by willsongbo** [comment]
hello，
       I've updated the link. You can try it.
       To BTW：Yes，The latest stable version is Sodium-SR1。
       And sorry，I haven't developed the version of Sodium yet（I may try to develop one later）, but you can refer to my documents. There is no big difference between Sodium and Oxygen with development.
      You can also refer to the official demo project of Odl-Sodium-SR1:
 samples：**https://github.com/opendaylight/controller/tree/release/sodium-sr1/opendaylight/md-sal/samples**

**Comment by empqruy** [comment]
Thanks @willsongbo
